# Hauteur Y à laquelle les joueurs sont téléportés au spawn pour éviter la mort par chute.
void-teleport-y: 0

# Configuration de l'item qui ouvre le menu des serveurs
selector-item:
  slot: 0
  name: '&aMenu des Jeux &7(Clic Droit)'
  lore:
    - '&7Ouvre le menu pour choisir ton jeu !'
  # ID de la tête depuis le plugin HeadDatabase
  head-id: '33202'
  # Le matériau ci-dessous ne sera utilisé que si HeadDatabase n'est pas trouvé
  fallback-material: COMPASS

# Mondes considérés comme des lobbys
lobby-worlds:
  - 'lobby'
  - 'world'

protection:
  # Activer ou désactiver toutes les protections du lobby
  enabled: true

  # Bloquer le temps à une valeur fixe (6000 = midi)
  lock-time-to: 6000

scoreboard:
  enabled: true
  # Intervalle de rafraîchissement en ticks (20 ticks = 1 seconde)
  update-interval: 40

tablist:
  enabled: true
  # Intervalle de rafraîchissement en ticks (20 ticks = 1 seconde)
  update-interval: 40

player-experience:
  # Messages de connexion et de déconnexion personnalisés
  join-leave-messages:
    enabled: true
    join: "&8[&a+&8] &7%player_name%"
    leave: "&8[&c-&8] &7%player_name%"

  # Gestion de la visibilité des joueurs
  player-visibility:
    enabled: true
    item-slot: 8
    cooldown-seconds: 3 # Temps de rechargement entre chaque utilisation
    item-name: '&aVisibilité des Joueurs &7(Clic Droit)'
    item-lore:
      - '&7Cliquez pour changer les joueurs'
      - '&7que vous voyez dans le lobby.'
    # Matériau de l'item pour chaque état : TOUS, VIPs, PERSONNE
    item-all: LIME_DYE
    item-vips: YELLOW_DYE
    item-none: GRAY_DYE

  # Plaques de saut
  launchpads:
    enabled: true
    plate-material: STONE_PRESSURE_PLATE
    block-material: IRON_BLOCK
    power-vertical: 1.8 # Force de la propulsion vers le haut
    power-horizontal: 2.2 # Force de la propulsion vers l'avant
    sound: ENTITY_BAT_TAKEOFF

interface-and-chat:
  # Titre affiché à l'écran lors de la connexion
  welcome-title:
    enabled: true
    # Le titre principal qui reste affiché pendant toute la séquence
    main-title:
      text: "<gradient:#FF8000:#FFD700><bold>H E N E R I A</bold></gradient>"
      fade-in: 1
      stay: 5 # Reste 5 secondes au total
      fade-out: 1

    # Liste des sous-titres qui s'afficheront en séquence
    subtitles:
      - text: "&eBienvenue, %player_name% !"
        fade-in: 0.5
        stay: 2
        fade-out: 0.5
      - text: "&fDécouvrez nos jeux : &cBedwars&f, &aZombie&f, &5Nexus &f!"
        fade-in: 0.5
        stay: 2
        fade-out: 0.5

  # Formatage du chat
  chat-format:
    enabled: true
    # Placeholders : %vault_prefix%, %player_name%, %message%
    format: "%vault_prefix% &7%player_name% &8» &f%message%"
holograms:
  # Intervalle de rafraîchissement en ticks (20 ticks = 1 seconde)
  update-interval: 100

party-sheep:
  enabled: true
  max-sheep-count: 10
  spawn-check-interval-seconds: 30
  respawn-delay-seconds: 10
  hit-effects:
    sound: "ENTITY_CHICKEN_EGG"
    particle: "NOTE"
  launch-effects:
    sound: "ENTITY_GENERIC_EXPLODE"
    particle: "EXPLOSION"
    launch-power: 1.5
