# Hauteur Y à laquelle les joueurs sont téléportés au spawn pour éviter la mort par chute.
void-teleport-y: 0

# Configuration de l'item qui ouvre le menu des serveurs
selector-item:
  slot: 0
  name: '&aMenu des Jeux &7(Clic Droit)'
  lore:
    - '&7Ouvre le menu pour choisir ton jeu !'
  # Texture Base64 pour la tête "Terre"
  texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6InRlc3QifX19"

protection:
  # Activer ou désactiver toutes les protections du lobby
  enabled: true

  # Les protections ne seront actives que dans les mondes listés ici
  lobby-worlds:
    - 'lobby'
    - 'world'

  # Bloquer le temps à une valeur fixe (6000 = midi)
  lock-time-to: 6000
