# Hauteur Y à laquelle les joueurs sont téléportés au spawn pour éviter la mort par chute.
void-teleport-y: 0

# Configuration de l'item qui ouvre le menu des serveurs
selector-item:
  slot: 0
  name: '&aMenu des Jeux &7(Clic Droit)'
  lore:
    - '&7Ouvre le menu pour choisir ton jeu !'
  # Texture Base64 pour la tête "Terre"
  texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6InRlc3QifX19"

# Mondes considérés comme des lobbys
lobby-worlds:
  - 'lobby'
  - 'world'

protection:
  # Activer ou désactiver toutes les protections du lobby
  enabled: true

  # Bloquer le temps à une valeur fixe (6000 = midi)
  lock-time-to: 6000

scoreboard:
  enabled: true
  # Intervalle de rafraîchissement en ticks (20 ticks = 1 seconde)
  update-interval: 40

tablist:
  enabled: true
  # Intervalle de rafraîchissement en ticks (20 ticks = 1 seconde)
  update-interval: 40

player-experience:
  # Messages de connexion et de déconnexion personnalisés
  join-leave-messages:
    enabled: true
    join: "&8[&a+&8] &7%player_name%"
    leave: "&8[&c-&8] &7%player_name%"

  # Gestion de la visibilité des joueurs
  player-visibility:
    enabled: true
    item-slot: 8
    # Matériau de l'item pour chaque état : TOUS, VIPs, PERSONNE
    item-all: LIME_DYE
    item-vips: YELLOW_DYE
    item-none: GRAY_DYE

  # Plaques de saut
  launchpads:
    enabled: true
    plate-material: STONE_PRESSURE_PLATE
    block-material: IRON_BLOCK
    power-vertical: 1.8 # Force de la propulsion vers le haut
    power-horizontal: 2.2 # Force de la propulsion vers l'avant
    sound: ENTITY_BAT_TAKEOFF

interface-and-chat:
  # Titre affiché à l'écran lors de la connexion
  welcome-title:
    enabled: true
    title: "&6&lHENERIA"
    subtitle: "&eBienvenue, %player_name% !"
    fade-in: 1  # en secondes
    stay: 3     # en secondes
    fade-out: 1 # en secondes

  # Formatage du chat
  chat-format:
    enabled: true
    # Placeholders : %vault_prefix%, %player_name%, %message%
    format: "%vault_prefix% &7%player_name% &8» &f%message%"
holograms:
  # Intervalle de rafraîchissement en ticks (20 ticks = 1 seconde)
  update-interval: 100
