name: HeneriaLobby
main: net.heneria.henerialobby.HeneriaLobby
version: 1.6.0
api-version: '1.21'
author: Heneria
description: Central lobby plugin for the Heneria network
softdepend: [PlaceholderAPI]
commands:
  lobby:
    description: "Teleportation vers le spawn du lobby"
    usage: "/lobby"
  setlobby:
    description: "Définit le spawn du lobby"
    usage: "/setlobby"
    permission: heneria.lobby.admin
  servers:
    description: "Ouvre le menu de sélection des serveurs"
    usage: "/servers"
  lobbyadmin:
    description: "Commandes d'administration du lobby"
    usage: "/lobbyadmin reload"
    permission: heneria.lobby.admin.reload
permissions:
  heneria.lobby.admin:
    description: "Permet de configurer le spawn du lobby"
    default: op
  heneria.lobby.canbeseen:
    description: "Permet d'être vu en mode VIP."
    default: false
  heneria.lobby.admin.reload:
    description: "Permet de recharger le plugin"
    default: op
