name: HeneriaLobby
main: net.heneria.henerialobby.HeneriaLobby
version: 1.10.0
api-version: '1.21'
author: Heneria
description: Central lobby plugin for the Heneria network
softdepend: [PlaceholderAPI]
commands:
  lobby:
    description: "Teleportation vers le spawn du lobby"
    usage: "/lobby"
  setlobby:
    description: "Définit le spawn du lobby"
    usage: "/setlobby"
    permission: heneria.lobby.admin
  servers:
    description: "Ouvre le menu de sélection des serveurs"
    usage: "/servers"
  lobbyadmin:
    description: "Commandes d'administration du lobby"
    usage: "/lobbyadmin reload"
    permission: heneria.lobby.admin.reload
  hologram:
    description: "Gestion des hologrammes"
    usage: "/hologram <create|delete|addline|setline|movehere>"
    permission: heneria.lobby.admin.hologram
  npc:
    description: "Gestion des PNJ"
    usage: "/npc <create|delete|select|move|skin|equip|unequip|link|help>"
    permission: heneria.lobby.admin.npc
permissions:
  heneria.lobby.admin:
    description: "Permet de configurer le spawn du lobby"
    default: op
  heneria.lobby.canbeseen:
    description: "Permet d'être vu en mode VIP."
    default: false
  heneria.lobby.admin.reload:
    description: "Permet de recharger le plugin"
    default: op
  heneria.lobby.chatcolor:
    description: "Permet d'utiliser les codes couleurs dans le chat"
    default: false
  heneria.lobby.admin.hologram:
    description: "Permet de gérer les hologrammes"
    default: op
  heneria.lobby.admin.npc:
    description: "Permet de gérer les PNJ"
    default: op
