name: HeneriaLobby
main: net.heneria.henerialobby.HeneriaLobby
version: 1.0.0
api-version: '1.21'
author: Heneria
description: Central lobby plugin for the Heneria network
softdepend: [PlaceholderAPI]
